//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapyWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class T_FB_USER
    {
        [Key]
        [Column(TypeName = "VARCHAR")]
        [StringLength(150)]
        public string from_id { get; set; }
        [StringLength(150)]
        public string name { get; set; }
    }
}
