//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TweetSet
    {
        public string Tweet_Id { get; set; }
        public string TweetText { get; set; }
        public System.DateTime DateDownload { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string HashTags { get; set; }
        public string Mentions { get; set; }
        public string UserId { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public Nullable<int> FriendsCouunt { get; set; }
        public string PlaceName { get; set; }
        public string PlaceId { get; set; }
        public string LatLong { get; set; }
        public string Language { get; set; }
    }
}
