//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TweetSet
    {
        public string Tweet_Id { get; set; }
        public string TweetText { get; set; }
        public System.DateTime DateDownload { get; set; }
    }
}
