// <auto-generated />
namespace ScrapyWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FBAccess_CompositeKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FBAccess_CompositeKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111752136_FBAccess_CompositeKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
