// <auto-generated />
namespace ScrapyWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FBAccess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FBAccess));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081119089_FBAccess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
