// <auto-generated />
namespace ScrapyWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newCommentsWaiting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newCommentsWaiting));
        
        string IMigrationMetadata.Id
        {
            get { return "201801261828379_newCommentsWaiting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
